CREATE USER 
'CRM'@'localhost' 
IDENTIFIED  BY 'Crm2526$';

GRANT USAGE ON *.* TO 'CRM'@'localhost';

ALTER USER 'CRM'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON CRM.* 
TO 'CRM'@'localhost';

FLUSH PRIVILEGES;
